openapi: "3.1.0"

info:
  title: GLIMPS Malware - Detect
  description: This API allows user to submit binary files to be analyzed
  version: '2.6.0'

tags:
  - name: submit
  - name: result
  - name: search
  - name: status
  - name: url

paths:
  /submit:
    post:
      summary: Submit a file to be analyzed
      description: |
        Send a file to platform for analyze this.
        The response content an UUID for view result when is treatment is ending.
      security:
        - ApiAuthKey: []
      tags:
        - submit
      parameters:
        - name: bypass-cache
          in: query
          required: false
          schema:
            type: boolean
          example: false
          description: ask API to bypass cache and always submit file to orchestrator (optional)
        - name: dynamic
          in: query
          required: false
          schema:
            type: boolean
          example: false
          description: select the profile's dynamic services. Is forced to true by default with the profile param force_dynamic 
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                tags:
                  type: string
                  description: user tags, each tag separated by a ','
                archive_password:
                  type: string
                  description: password used to extract archive
                bypass-cache:
                  type: boolean
                  description: ask API to bypass cache and always submit file to orchestrator
                description:
                  type: string
                  description: custom description for analysis
              required:
                - file
      responses:
        '200':
          description: file submitted
          content:
            application/json:
              schema:
                type: object
                required:
                  - "status"
                properties:
                  status:
                    $ref: "#/components/schemas/submitStatus"
                  uuid:
                    $ref: "#/components/schemas/uuid"
                  error:
                    $ref: "#/components/schemas/error"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '429':
          description: user reach her quota
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/errorResponse"
              examples:
                quota-exceeded:
                  description: user exceeded her daily quota (number of submission in 24h)
                  value:
                    status: false
                    error: "quota exceeded, try again in 24h"
        '500':
          $ref: '#/components/responses/InternalServerError'
  /results:
    get:
      summary: Returns results by date (from -> to) in seconds
      description: Returns results by date (from -> to) in seconds
      security:
        - ApiAuthKey: []
      tags:
        - result
      parameters:
        - name: from
          in: query
          schema: 
            type: integer
            minimum: 0
            default: 86400
            example: 86400
          description: |
            Results *from* now minus this value in seconds will be returned

            Here 86400 seconds for one day
        - name: to
          in: query
          schema: 
            type: integer
            minimum: 0
            default: 0
            example: 86400
          description: |
            Results *until* now minus this value in seconds will be returned
            
            Here 86400 seconds for one day
        - name: size
          in: query
          schema:
            type: integer
            minimum: 0
            default: 10
            example: 15
          description: Number of results to be returned
        - name: offset
          in: query
          schema:
            minimum: 0
            type: integer
            default: 0
            example: 10
          description: Offset to be applied to the returned results index
        - name: tags
          in: query
          schema:
            type: array
            items:
              type: string
          description: filter on user tags
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/resultsByDate"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /results/{UUID}:
    get:
      summary: Retrieve the analysis
      description: 'Retrieve analysis with their UUID'
      security:
        - ApiAuthKey: []
      tags:
        - result
      parameters:
        - name: UUID
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/uuid"
        - name: wait
          in: query
          required: false
          schema:
            type: integer
          description: the maximum number of seconds to wait for the result to be done.
      responses:
        '200':
          description: 'Request is correct, return data about result'
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/analysis"
              examples:
                Analysis:
                  $ref: "#/components/examples/analysis"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /results/{UUID}/full:
    get:
      summary: Retrieve full analysis
      description: Retrieve full analysis
      security:
        - ApiAuthKey: []
      tags:
        - result
      parameters:
        - name: UUID
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/uuid"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/fullAnalysis"
              examples:
                analysis:
                  $ref: "#/components/examples/fullAnalysis"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /results/{UUID}/export:
    get:
      security:
        - ApiAuthKey: []
      tags:
        - result
      description: |
        Exports a specific analysis result by giving its Uuid. \
        Exports Formats can be Misp, Stix, Json, Pdf, Markdown and Csv. \
        Submitter must have the TODO permissions. \
      parameters:
        - name: "UUID"
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/uuid"
        - name: "format"
          in: query
          description: "Format defines the export's format: misp, stix, json, pdf, markdown or csv"
          schema:
            type: string
            enum: [misp, stix, json, pdf, markdown, csv]
          required: true
        - name: "full"
          in: query
          description: "Full defines if export must be full analysis or summarized"
          schema:
            type: boolean
            enum: [true, false]
          required: false
        - name: "layout"
          in: query
          description: "Layout defines the report's language layout: fr or en"
          schema:
            type: string
            enum: [fr, en]
          required: true
      responses:
        '200':
          description: The file is available and is directly returned to the client. The mimetype depends on the returned file
          content:
            application/octet-stream:
              schema:
                type: string
              examples:
                misp:
                  value: >
                    {
                        "Event": {
                            "published": true,
                            "extends_uuid": "",
                            "date": "2022-06-28",
                            "publish_timestamp": "1656408487",
                            "uuid": "7b644791-56f2-413b-9b49-4b03ad9e849b",
                            "threat_level_id": "3",
                            "timestamp": "1656408487",
                            "info": "Glimps Malware - Analysis of file InstallEngine_x64.bin",
                            "analysis": "2",
                            "Orgc": {
                                "uuid": "81a2e0d4-cf48-481f-8fc4-8f0b89b7066a",
                    ...

                    }
                stix:
                  value: >
                    {
                      "type": "bundle",
                      "id": "bundle--177a93b4-3498-4d10-a6e3-c312572871cd",
                      "objects": [
                        {
                          "type": "file",
                          "spec_version": "2.1",
                          "id": "file--2418e841-9cc7-4d91-b6f0-084d515972ae",
                          "created": "2022-06-28T09:25:19.458Z",
                          "modified": "2022-06-28T09:25:19.458Z",
                          "name": "InstallEngine_x64.bin",
                          "Hashes": {
                            "MD5": "01e59bff8f354b38d0c3e4caad2208d7",
                      ...

                      }
                pdf:
                  value: >
                    %PDF-1.3
                    3 0 obj
                    <</Type /Page
                    /Parent 1 0 R
                    /Resources 2 0 R
                    /Contents 4 0 R>>
                    endobj
                    4 0 obj
                    <</Filter /FlateDecode /Length 2744>>
                    stream
                json:
                  value: >
                    {
                        "Verdict": "malicious",
                        "Score": 2800,
                        "Family": ["AutoIT-17.UNOFFICIAL", "HEUR/AGEN.1245831", "auto_it"],
                        "Filename": "InstallEngine_x64.bin",
                        "SubmissionDate": "2022-06-09T16:04:25.513303Z",
                        "CompletionDate": "2022-06-09T16:04:45.89212Z",
                    ...

                    }
                csv:
                  value: >
                    name,sha256,size,human file size,score,verdict,mimetype

                    ef9b9bdb48b119dbd0e1cab3f604978eedd72e4ee2adb1a49219f84a75d3b6f0.unUPX,b160c9c0964f16f54826190a43b5f0edd59660f9ac245971d6b7e56fa6c43adf,1126304,1.1 MiB,2800,malicious,application/x-dosexec
                markdown:
                  value: >
                    # GMalware submission report: export.tgz

                    **Result**: safe

                    **Score**: 0

                    **Family**:

                    ## General information

                    **Name**: export.tgz

                    **Description**: Inspection of file: export.tgz

                    **Analysis submitted on**: Wed Jun 15, 2022 14:21:56 UTC

                    **Analysis completed on**: Wed Jun 15, 2022 14:22:33 UTC

                    ...
        '400':
          $ref: "#/components/responses/BadRequest"
        '403':
          $ref: "#/components/responses/Forbidden"
        '404':
          $ref: "#/components/responses/NotFound"
  /search/{sha256}:
    get:
      summary: Search a previous analysis
      description: Search a previous analysis
      security:
        - ApiAuthKey: []
      tags:
        - search
      parameters:
        - name: sha256
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/sha256"
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/analysis"
              examples:
                Analysis Completed Minimal:
                  $ref: "#/components/examples/analysis"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /results/{UUID}/{SHA256}/service/{SERVICE}:
    get:
      summary: get JSON body result for a given service and an analysis file
      description: get JSON body result
      security:
        - ApiAuthKey: []
      tags:
        - result
      parameters:
        - name: UUID
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/uuid"
        - name: SHA256
          in: path
          required: true
          schema:
            $ref:  "#/components/schemas/sha256"
        - name: SERVICE
          in: path
          required: true
          schema:
            $ref: "#/components/schemas/service"
      responses:
        '200':
          description: service result
          content:
            application/json:
              schema:
               type: object 
              examples:
                SignatureUmbrella:
                  value:
                    av_name: "signature_umbrella"
                    av_version: "8.3.64.72"
                    db_version: "8.19.2.26"
                    malware: true
                    malware_name: "TR/Crypt.XPACK.Gen"
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /status:
    get:
      operationId: getProfileStatus
      summary: Get profile status.
      description: Get profile status. The status will contains quota state and an estimation of analysis duration.
      security:
        - ApiAuthKey: []
      tags:
        - status
      responses:
        '200':
          description: profile status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/profileStatus"
              examples:
                static:
                  $ref: "#/components/examples/static"
  /url:
    post:
      description: Send an URL and return an verdict
      security:
        - ApiAuthKey: []
      tags:
        - url
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  description: "URL to test"
      responses:
        '200':
          description: "URL tested"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/URLTestSchemasResponseOK'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  responses:
    BadRequest:
      description: "Bad Request, wrong syntax"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/badRequest"
          examples:
            'anonymous archive':
              description: anonymous user try to submit archive file
              value:
                status: false
                error: invalid filetype
                details: [{"file": "invalid filetype"}]
            'invalid file size':
              description: submitted file size is bigger than limit
              value:
                status: false
                error: bad request
                details: [{"file": "invalid file size (0<size<95.4 mib)"}]
            'file is required':
              description: file is required
              value:
                status: false
                error: bad request
                details: [{"file": "file is required"}]
            'invalid request parameter':
              description: user used an invalid request parameter
              value:
                status: false
                error: "bad request"
                details: [{"key": "error description"}]
            'bad request':
              value:
                status: false
                error: "bad request"
    Forbidden:
      description: user try to submit a file without submit permission
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
          examples:
            bypass-cache:
              description: user without bypass cache permission tried to bypass cache
              value:
                status: false
                error: "bypass-cache denied"
            submit:
              description: user without submit permission tried to submit a file
              value:
                status: false
                error: "submit denied"
            search:
              description: user without search permission tried to search a result
              value:
                status: false
                error: "search denied"
            forbidden:
              description: user without search permission try to request search
              value:
                status: false
                error: "forbidden"
    NotFound:
      description: user try to access resources that does not exist
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
          examples:
            notfound:
              value:
                status: false
                error: "not found"
    InternalServerError:
      description: unexpected error from server
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/errorResponse"
          examples:
            internalServerError:
              value:
                status: false
                error: "internal server error"
    Unauthorized:
      description: "Unauthorized, authentication is mandatory"
      content:
        application/json:
          schema:
             $ref: "#/components/schemas/errorResponse"
          examples:
            unauthorized:
              value:
                status: false
                error: "unauthorized"
  securitySchemes:
    ApiAuthKey:
      type: apiKey
      in: header
      name: X-Auth-Token
      description: |
        Authentication token for the lite api
  schemas:
    submitStatus:
      type: boolean
      description: |
        true => analysis in progress,
        false => an error occurred
    badRequest:
      type: object
      properties:
        status:
          default: false
          type: boolean
          description: false => an error occurred
        error:
          type: string
          description: string describing error 
        details:
          type: array
          description: human readable message for each key in error
          items:
            type: object
    errorResponse:
      type: object
      required:
        - "status"
      properties:
        status:
          default: false
          type: boolean
          description: false => an error occurred
        error:
          type: string
          description: string describing error
    resultsByDate:
      type: object
      properties:
        count: 
          type: integer
          example: 1
        submissions:
          type: array
          items:
            type: object
            properties:
              uuid:
                $ref: "#/components/schemas/uuid"
              is_malware:
                $ref: "#/components/schemas/is_malware"
              done:
                $ref: "#/components/schemas/done"
              error:
                $ref: "#/components/schemas/error"
              filename:
                $ref: "#/components/schemas/filename"
              date:
                $ref: "#/components/schemas/timestamp"
              file_size:
                $ref: "#/components/schemas/size"
              file_type:
                $ref: "#/components/schemas/filetype"
              score:
                $ref: "#/components/schemas/score"
              malwares:
                $ref: "#/components/schemas/malwares"
              special_status_code:
                $ref: "#/components/schemas/special_status_code"
            example: 
              items:
                - uuid: "6ed43200-4789-4ab5-ad19-064469c129dd"
                  is_malware: true
                  done: true
                  error: false
                  filename: "test.bin"
                  date: 1675850874780
                  file_size: 12340
                  file_type: "zip"
                  score: 1200
                  malwares: ["eicar"]
                  special_status_code: 103
                - uuid: "6ed43200-4789-4ab5-ad19-064469c129ee"
                  is_malware: false
                  done: false
                  error: false
                  filename: "test.exe"
                  date: 1675850071234
                  file_size: 1234
                  file_type: "exe"
                  score: 0
                  malwares: []
                  special_status_code: 0
    analysis:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/status"
        uuid:
          $ref: "#/components/schemas/uuid"
        sid:
          $ref: "#/components/schemas/sid"
        sha256:
          $ref: "#/components/schemas/sha256"
        sha1:
          $ref: "#/components/schemas/sha1"
        md5:
          $ref: "#/components/schemas/md5"
        ssdeep:
          $ref: "#/components/schemas/ssdeep"
        is_malware:
          $ref: "#/components/schemas/is_malware"
        score:
          $ref: "#/components/schemas/score"
        done:
          $ref: "#/components/schemas/done"
        timestamp:
          $ref: "#/components/schemas/timestamp"
        duration:
          $ref: "#/components/schemas/duration"
        error:
          $ref: "#/components/schemas/error"
        errors:
          $ref: "#/components/schemas/errors"
        filetype:
          $ref: "#/components/schemas/filetype"
        size:
          $ref: "#/components/schemas/size"
        filenames:
          $ref: "#/components/schemas/filenames"
        files:
          $ref: "#/components/schemas/files"
        file_count:
          $ref: "#/components/schemas/file_count"
        token:
          $ref: "#/components/schemas/view_token"
        malwares:
          $ref: "#/components/schemas/malwares"
        threats:
          $ref: "#/components/schemas/threats"
        special_status_code:
          $ref: "#/components/schemas/special_status_code"
      required:
        - status
        - UUID
        - sid
        - sha256
        - sha1
        - md5
        - ssdeep
        - is_malware
        - score
        - done
        - timestamp
        - duration
        - filetype
        - filecount
        - special_status_code
    fullAnalysis:
      type: object
      properties:
        archive_ts:
          $ref: "#/components/schemas/archive_ts"
        classification:
          $ref: "#/components/schemas/classification"
        error_count:
          $ref: "#/components/schemas/error_count"
        errors:
          $ref: "#/components/schemas/errors"
        expiry_ts:
          $ref: "#/components/schemas/expiry_ts"
        file_count:
          $ref: "#/components/schemas/file_count"
        file_infos:
          $ref: "#/components/schemas/file_infos"
        file_tree:
          $ref: "#/components/schemas/file_tree"
        files:
          $ref: "#/components/schemas/files"
        max_score:
          $ref: "#/components/schemas/max_score"
        metadata:
          $ref: "#/components/schemas/metadata"
        missing_error_keys:
          $ref: "#/components/schemas/missing_error_keys"
        missing_result_keys:
          $ref: "#/components/schemas/missing_result_keys"
        params:
          $ref: "#/components/schemas/params"
        results:
          $ref: "#/components/schemas/results"
        sid:
          $ref: "#/components/schemas/sid"
        state:
          $ref: "#/components/schemas/state"
        times:
          $ref: "#/components/schemas/times"
        verdict:
          $ref: "#/components/schemas/verdict"
        special_status_code:
          $ref: "#/components/schemas/special_status_code"
      required:
        - archive_ts
        - classification
        - error_count
        - expiry_ts
        - file_count
        - file_infos
        - file_tree
        - files
        - max_score
        - metadata
        - missing_error_keys
        - missing_result_keys
        - params
        - results
        - sid
        - state
        - times
        - verdict
        - special_status_code
    archive_ts:
      type: string
      example: "2024-04-19T11:54:46.398882Z"
    classification:
      type: string
    error_count:
      type: integer
    expiry_ts:
      type: string
    file_infos:
      description: file information
      type: object
    file_tree:
      type: object
    max_score:
      type: integer
    metadata:
      type: object
    missing_error_keys:
      type: array
      items:
        type: string
    missing_result_keys:
      type: array
      items:
        type: string
    params:
      type: object
    results:
      type: object
    state:
      type: string
    times:
      type: object
    verdict:
      type: object
    status:
      type: boolean
      description: |
        true => no error to report,
        false => an error occurred
    sid:
      description: |
        analysis UUID handled by GLIMPS malware finder - expert
        could be used to construct expert link like:
        https://gmalware.useddomain.glimps.re/expert/en/analysis/results/advanced/${SID}
      type: string
      example: 2z4zfg66Sm3k0Y2KcjgqoK
    uuid:
      type: string
      description: |
        Unique analysis identifier
      example: "9618ae7e-e284-405d-8998-ff1e12c7ca27"
    sha256:
      type: string
      description: string hex encoded input file SHA256
      example: "c253396cf740b03629b1a76f071eb3594099eebc130f47ae8fe15ef47679e209"
    sha1:
      type: string
      description: string hex encoded input file SHA1
      example: "f9a0a612aa694acc24726ed8610981db9798dde0"
    md5:
      type: string
      description: string hex encoded input file MD5
      example: "8437115b99341df5becdb03a4d091654"
    ssdeep:
      type: string
      description: string input file SSDeep
      example: "384:4fpWcehzJFYKWYGWhdffa3zWzc3fpCLrsjHIX69URc+hmnulY1qHprFKt6zW8zZn:4fkcY/WYf/ffa3axfpWcehzJFYKWYGWv"
    is_malware:
      type: boolean
      description: analysis result, is a malware or not
    score:
      type: integer
      description: highest score given by probes
      example: 1000
    done:
      type: boolean
      description: is the analysis finished
    timestamp:
      type: integer
      description: |
        timestamp of the start of analysis in milliseconds
        timestamp is 0 for anonymous user
    duration:
      type: integer
      description: duration of the analysis in milliseconds
      example: 998
    error:
      type: string
      description: error message if Status is false
    errors:
      type: object
      description: error message by services
      additionalProperties:
        type: string
    filetype:
      type: string
      description: ''
    size:
      type: integer
      description: input file size (in bytes)
    magic:
      type: string
      description: file magic - file type
    file_count:
      description: amount of file in the submission (input + extracted)
      type: integer
      example: 1
    filename:
      type: string
      description: name of the input file
    filenames:
      type: array
      description: list of analyzed filename
      items:
        type: string
    files:
      description: array of submission files (input file and extracted sub-files)
      type: array
      items:
        $ref: "#/components/schemas/fileEntry"
    fileEntry:
      description: file information
      type: object
      properties:
        sha256:
          $ref: "#/components/schemas/sha256"
        sha1:
          $ref: "#/components/schemas/sha1"
        md5:
          $ref: "#/components/schemas/md5"
        ssdeep:
          $ref: "#/components/schemas/ssdeep"
        magic:
          $ref: "#/components/schemas/magic"
        av_results:
          $ref: "#/components/schemas/av_results"
        size:
          $ref: "#/components/schemas/size"
        is_malware:
          $ref: "#/components/schemas/is_malware"
    av_results:
      description: malware matches returns by probes, print av_result right required
      type: object
      properties:
        av:
          type: string
          description: probe name
          example: "GlimpsCorrelate"
        result:
          type: string
          description: malware name indicated by probe
          example: win_cybergate_auto
        score:
          type: integer
          description: amount of point added by the probe
          example: 1000
    view_token:
      description: token that can be used to view analysis result in expert view
      type: string
    malwares:
      type: array
      description: list of malware names found in analysis
      items:
        type: string
    service:
      type: string
      description: service name
      example: GlimpsCorrelate
    threats:
      description: |
        Summary of threats found in submission.
        Each submission file reaching threshold score will add an entry.
        Entry keys are the SHA256 of files
      type: object
      additionalProperties:
        type: object
        properties:
          filenames:
            $ref: "#/components/schemas/filenames"
          tags:
            description: list of tag of interest
            type: array
            items:
              type: object
              properties:
                name:
                  type: string
                  description: tag name
                value:
                  type: string
                  description: tag value
          score:
            $ref: "#/components/schemas/score"
          magic:
            $ref: "#/components/schemas/magic"
          sha256:
            $ref: "#/components/schemas/sha256"
          sha1:
            $ref: "#/components/schemas/sha1"
          md5:
            $ref: "#/components/schemas/md5"
          ssdeep:
            $ref: "#/components/schemas/ssdeep"
          file_size:
            $ref: "#/components/schemas/size"
          mime:
            $ref: "#/components/schemas/mime"
    mime:
      type: string
      description: file mime type
      example: text/plain
    special_status_code:
      type: integer
      description: "Code identifying a special case among:\n
        - case 1 -> archive extraction failed\n
          \t- sub-case 1 -> archive password unknown, code=101\n
          \t- sub-case 2 -> too many files in archive or file too big, code=102\n
        - case 2 -> no signatures in result, code=103\n
        - case 3 -> negative score (whitelisted file), code=104\n\n
        - case 4 -> only a filtering service is in error, code=105\n\n
        If no special case, **code=0**.\n\n
        If multiple cases match, the code is given following the priority order: 104, 101, 102, 103
        "
      example: 103
    profileStatus:
      type: object
      description: status of a profile
      properties:
        monthly_submission_quota:
          type: integer
          description: |
            Maximum number of submissions allowed in a month.
            0 => unlimited.
        monthly_volume_quota:
          type: integer
          format: int64
          description: |
            Maximum volume of data in bytes allowed in a month.
            0 => unlimited.
        parallel_submission_quota:
          type: integer
          description: |
            Maximum number of concurrent submissions allowed.
            0 => unlimited.
        available_monthly_submissions:
          type: integer
          description: |
            number of submissions still available for the month.
            0 => unlimited.
        available_monthly_volume:
          type: integer
          format: int64
          description: |
            volume of data in bytes still available for the month.
            0 => unlimited.
        available_parallel:
          type: integer
          description: |
            number of concurrent submissions still available.
            0 => unlimited.
        cache:
          type: boolean
          description: true if detect (SHA256 based) cache is activated for the profile.
        estimated_analysis_duration:
          type: integer
          description: |
            An estimation of the duration used by the next analysis in milliseconds.
            It's an optimistic estimation, taking into account the average duration of each service and the state of the orchestrator.
        malware_threshold:
          type: integer
          description: Analysis score from which an input file is classified as a malware
    URLTestSchemasResponseOK:
      type: object
      properties:
        verdict:
          type: string
          description: "category of menace: unknown / safe / suspicious / malicious"
        matches:
          type: object
  examples:
    analysis:
      value:
        status: true
        UUID: "9618ae7e-e284-405d-8998-ff1e12c7ca27"
        sid: "1HLXVrb5dMFrXpgSTGnScd"
        sha256: "c253396cf740b03629b1a76f071eb3594099eebc130f47ae8fe15ef47679e209"
        sha1: "f9a0a612aa694acc24726ed8610981db9798dde0"
        md5: "8437115b99341df5becdb03a4d091654"
        ssdeep: "384:4fpWcehzJFYKWYGWhdffa3zWzc3fpCLrsjHIX69URc+hmnulY1qHprFKt6zW8zZn:4fkcY/WYf/ffa3axfpWcehzJFYKWYGWv"
        is_malware: true
        done: true
        timestamp: 1637835534067
        filetype: "elf"
        size: 31976
        special_status_code: 103
        score: 42
        duration: 42
        filecount: 24
    fullAnalysis:
      value:
        archive_ts: "2024-04-19T11:54:46.398882Z"
        classification: TLP:w
        error_count: 0
        expiry_ts: "2024-05-04T13:13:59.966459Z"
        file_count: 1
        file_infos: 
          $ref: "#/components/schemas/file_infos"
        file_tree: 
          $ref: "#/components/schemas/file_tree"
        max_score: 0
        metadata:
          $ref: "#/components/schemas/metadata"
        files: 
          - file:
            type: object
        missing_error_keys: ["error_key"]
        missing_result_keys: ["result_key"]
        params:
          $ref: "#/components/schemas/params"
        results: {}
        sid: "1c15LZo0vU1GiRGDiy8OCC"
        state: "completed"
        times: { "completed": "2024-04-04T13:14:01.852268Z", "submitted": "2024-04-04T13:13:59.966457Z" }
        verdict: { "malicious": [], "non_malicious": [] }
        special_status_code: 103
    static:
      value:
          daily_quota: 100000
          available_daily_quota: 100000
          cache: true
          estimated_analysis_duration: 2080

servers:
  - url: http://localhost:8081/api/lite/v2
    description: Local server
  - url: https://gmd.rd.glimps.lan/api/lite/v2
    description: Dev server
